source 'http://rubygems.org'
ruby '2.7.1'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'mysql2'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'carrierwave', '~> 2.0'
gem 'mini_magick'
gem 'securerandom'
gem 'activerecord-mysql-uuid-column'
gem 'activesupport'
